Добавляет обработчики для открытия и закрытия попапов, а также валида…
htmlacademy-javascript/1084415-keksobooking-21 pull request #5
Opened 2020-10-08 15:02 UTC by oderzhanie

…цию полей формы

2020-10-10 09:54 UTC, ElseeCCD requested changes

2020-10-10 09:54 UTC, ElseeCCD commented on js/main.js
> +  }
и тут тоже можно переписать с нашими новыми перечислениями и константами ) Создадим новую константу:
```
const OFFER_TYPES_TITLES_GENITIVE = {
  [Accommodation.FLAT]: `квартиры`,
  [Accommodation.HOUSE]: `дома`,
  [Accommodation.PALACE]: `дворца`
};
```
И тут всё сократим до 
```
if (priceValue > MAX_PRICE) {
    price.setCustomValidity(`Максимально допустимая стоимость - ${MAX_PRICE} руб.`);
  } else if (priceValue < MIN_PRICES[accType]) {
    price.setCustomValidity(`Минимальная стоимость для ${OFFER_TYPES_TITLES_GENITIVE[accType]} - ${MIN_PRICES[accType]} руб.`);
  } else {
    price.setCustomValidity(``);
  }
```

2020-10-10 09:54 UTC, ElseeCCD commented on js/main.js
> +  }
Наверно, хотела еще return написать внутри if, иначе выполнение функции не остановится и последняя строчка тоже выполнится, сделав, по сути, ненужное присваивание

2020-10-10 16:34 UTC, oderzhanie commented on js/main.js
> +      price.placeholder = MIN_PRICES.palace;
Как просто и красиво! Спасибо!

2020-10-12 17:48 UTC, ElseeCCD approved these changes

2020-10-12 17:48 UTC, ElseeCCD commented on js/main.js
> +  //   price.setCustomValidity(``);
так, комментарии нужно убрать )

2020-10-12 17:50 UTC, ElseeCCD commented on js/main.js
> +  imagesField.reportValidity();
кажется, для картинок одно и то же выполняется. Надо бы вынести в отдельную функцию checkImages какую-нибудь

2020-10-12 17:50 UTC, merged