Добавляет модуль для загрузки данных с сервера
htmlacademy-javascript/1084415-keksobooking-21 pull request #8
Opened 2020-10-21 17:52 UTC by oderzhanie

2020-10-21 18:04 UTC, oderzhanie commented on js/map.js
>        });
Вот к этой части у меня вопрос. Загрузка данных должна произойти после активации страницы, поэтому я положила ее в activatePage(). Тут же я дополняю серверные объекты айдишниками, потому что потом по айдишнику у меня сопоставляется объявление в метке и попап, который нужно отрисовать (код в файле popup.js).  Выходит, мне нужно передать в popup.js именно тот массив с айдишниками, который я получила в activatePage()? Но все эти манипуляции с массивом ограничены зоной видимости функции activatePage. Можно ли как-то вытащить массив из нее или же надо переписать код в popup.js, чтобы он не использовал id?

2020-10-22 18:24 UTC, ElseeCCD commented on js/map.js
>        });
Ну, самое простое, что я вижу в этой ситуации, это схитрить с генерацией id: составлять его исходя из location. Маловероятно, что нам попадутся 2 объявления в одном и ттом же месте (в любом случае, получить доступ к одному из них мы не сможем 😄 ). Т.е. сделать id=`${elem.location.x}-${elem.location.y}`. 
А в popup.js сделать так:
```
const pinCoords = pin.id.split("-");
const pinIndex = window.map.similarObjects.findIndex((element) => element.location.x === pinCoords[0] && element.location.y === pinCoords[1] );
```

2020-10-23 11:34 UTC, oderzhanie commented on js/map.js
>        });
@ElseeCCD А я тут все равно упираюсь в том, что массив similarObjects, который я внутри функции activateMap получила нужно каким-то образом передать в popup.js (потому что мне для отрисовки окна нужны остальные данные соответствующего объекта). А массив находится внутри функции, снаружи не виден. Выходит, тут или снова делать запрос к серверу в popup.js или как-то вытаскивать первое обращение к серверу из activateMap?

2020-10-23 11:55 UTC, ElseeCCD commented on js/constants.js
> +  const pinItems = 8;
это тоже должно быть большими буковками написано )

2020-10-24 08:12 UTC, ElseeCCD requested changes

2020-10-24 08:12 UTC, ElseeCCD commented on js/map.js
> +        similarObjects.push(elem);
так-так. Ты тут, получается, добавляешь в конец своего массива `similarObjects` точно такие же элменты, фактически дублируя их. Причем именно дублируя, т.к. `forEach` оперирует самими элементами массива, т.е. ты сначала добавляешь id к тому, что в массиве уже есть, а потом дублируешь этот элемент через push в конец массива. Вообще, кажется, я уже видела где-то этот код, проверь на дублирование, пожалуйста )

2020-10-24 08:12 UTC, ElseeCCD commented on js/popup.js
> +    if (photosLength === 0) {
можно не сравнивать с нулем, а переписать немного уловие:
```
if (photosLength) {
 // тут то, что сейчас в блоке else
}
else {
  cardPhotos.classList.add(`visually-hidden`);
}
```

2020-10-24 16:53 UTC, oderzhanie commented on js/map.js
> +        similarObjects.push(elem);
В этом месте фейспалм. Я перенесла этот код в data.js, а из map.js удалить забыла.

2020-10-25 13:00 UTC, ElseeCCD approved these changes

2020-10-25 13:00 UTC, merged